name: Integration

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - '*'
    paths:
      - 'src/controllers**'
jobs:
  linting-main-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies on auth-service
        working-directory: ./task-deel-backend
        run: yarn

      - name: Run ESLint
        working-directory: ./task-deel-backend
        run: yarn lint:check

      - name: Compile TSC
        working-directory: ./task-deel-backend/
        run: yarn build
